<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tuber" nsURI="http://www.example.org/tuber" nsPrefix="tuber">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="ecore.xml.type" value="http://www.eclipse.org/emf/2003/XMLType"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Agent" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rides" upperBound="-1"
        eType="#//Ride" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hires" upperBound="-1"
        eType="#//Driver" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enrolls" upperBound="-1"
        eType="#//Customer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" lowerBound="1" eType="#//City"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer" eSuperTypes="#//AppUser">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="inv4"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="inv4" value="Sequence {RideStatus::ONGOING, RideStatus::IDLE, RideStatus::REQUESTED} -> includes(self.status)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="payment" upperBound="-1"
        eType="#//Payment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="spendings" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Driver" eSuperTypes="#//AppUser">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="inv5"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="inv5" value="Sequence {RideStatus::ONGOING, RideStatus::IDLE} -> includes(self.status)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle" lowerBound="1"
        eType="#//Vehicle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="earnings" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AppUser" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//Location" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rating" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Float"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportCall" upperBound="-1"
        eType="#//HelpCentreCall" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="#//RideStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ride" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer" lowerBound="1"
        upperBound="-1" eType="#//Customer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver" lowerBound="1"
        eType="#//Driver"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="#//RideStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="payment" eType="#//Payment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Payment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//PaymentType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//VehicleType"
        defaultValueLiteral="CAR"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sharing" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lang" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lat" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" lowerBound="1" eType="#//City"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PaymentType">
    <eLiterals name="CREDITCARD"/>
    <eLiterals name="APPLEPAY" value="1"/>
    <eLiterals name="PAYPAL" value="2"/>
    <eLiterals name="CASH" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VehicleType">
    <eLiterals name="MOTORBIKE"/>
    <eLiterals name="CAR" value="1"/>
    <eLiterals name="LUXURY" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MotorRide" eSuperTypes="#//Ride">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="2.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CarRide" eSuperTypes="#//Ride">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="4.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LuxuryRide" eSuperTypes="#//Ride">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="10.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HelpCentreCall">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="inv10"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="inv10" value="(&#xA;&#x9;&#x9;&#x9;&#x9;self.type = IssueType::PAYMENT implies &#xA;&#x9;&#x9;&#x9;&#x9;&#x9;not self.ride.oclIsUndefined() &#xA;&#x9;&#x9;&#x9;&#x9;&#x9;and self.ride.status = RideStatus::COMPLETED &#xA;&#x9;&#x9;&#x9;&#x9;&#x9;and self.date >= self.ride.date&#xA;&#x9;&#x9;&#x9;) and (&#xA;&#x9;&#x9;&#x9;&#x9;self.type = IssueType::SAFETY implies &#xA;&#x9;&#x9;&#x9;&#x9;&#x9;not self.ride.oclIsUndefined() &#xA;&#x9;&#x9;&#x9;&#x9;&#x9;and self.date >= self.ride.date&#xA;&#x9;&#x9;&#x9;)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ride" eType="#//Ride"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Float"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="issue" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="#//TicketStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//IssueType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TUber" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agent" upperBound="-1"
        eType="#//Agent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="City">
    <eLiterals name="WIEN"/>
    <eLiterals name="SALZBURG" value="1"/>
    <eLiterals name="LINZ" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TicketStatus">
    <eLiterals name="RESOLVED"/>
    <eLiterals name="PENDING" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IssueType">
    <eLiterals name="PAYMENT"/>
    <eLiterals name="SAFETY" value="1"/>
    <eLiterals name="ACCOUNT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RideStatus">
    <eLiterals name="IDLE"/>
    <eLiterals name="ONGOING" value="1"/>
    <eLiterals name="REQUESTED" value="2"/>
    <eLiterals name="COMPLETED" value="3"/>
  </eClassifiers>
</ecore:EPackage>
